### ISSUE TITLE
Line number for check failure is wrong.

### ISSUE THREAD

**Issue by mustaphazorgati** [ScaCap/action-surefire-report#47]
After fixing #43 I realized that every failed test gets annotated with ` Check failure on line 1 in XXX`. 

I expected that the line number will be computed correctly. Unfortunately only `line 1` is shown.

Example Report: https://github.com/mustaphazorgati/taskana/runs/1840214460?check_suite_focus=true

**Comment by jmisur** [comment]
Fixed in `v1`.

**Comment by mustaphazorgati** [comment]
Unfortunately this is still not fixed.
I've tried `v1` and `v1.0.8`.
- Build: https://github.com/mustaphazorgati/taskana/runs/1916926316?check_suite_focus=true

**Comment by mustaphazorgati** [comment]
Hey @jmisur!
This issue is currently not fixed. I've tried again: https://github.com/mustaphazorgati/taskana/runs/2130607083?check_suite_focus=true

Please reopen this. :)

**Comment by mustaphazorgati** [comment]
Thanks for reopening! :)
If it helps: You can download the surefire xml files from the workflow: https://github.com/mustaphazorgati/taskana/actions/runs/661020161
Artifact-id: surefire-reports

**Comment by jmisur** [comment]
I checked your surefire results and found out an interesting piece (which I noticed previously but forgot about). Your testcase classname is a bit weird.
`<testcase name="should_SplitListIntoChunks_When_CallingPartitionBasedOnSize" classname="pro.taskana.common.api.CollectionUtilTest(H2)" time="0.049">`

I know you're running some test matrix setup which makes tests work on different dbs. How did you set this up? Is this something manual or out of the box? Is it always in this format `classname(strategy)` or it's a custom format? I need to know if I can take this example as the generic pattern so I can extract a raw classname from it. That's why line resolution doesn't work.

**Comment by mustaphazorgati** [comment]
Hey @jmisur,

> How did you set this up?
we use the maven property `surefire.reportNameSuffix` to add the information on which database the test ist executed.
See here: https://github.com/Taskana/taskana/pull/1536/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8

The documentation of the property can be found here: http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#reportNameSuffix

**Comment by mustaphazorgati** [comment]
Thank you for fixing this :)

**Comment by jmisur** [comment]
Fixed in v1.
